#![allow(dead_code)]

xflags::xflags! {
    src "./src/flags.rs"

    cmd xtask {
        /// Print help info.
        default cmd help {
            optional -h, --h
        }

        /// Run CI tests.
        cmd ci {}
    }
}

// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Xtask {
    pub subcommand: XtaskCmd,
}

#[derive(Debug)]
pub enum XtaskCmd {
    Help(Help),
    Ci(Ci),
}

#[derive(Debug)]
pub struct Help {
    pub h: bool,
}

#[derive(Debug)]
pub struct Ci;

impl Xtask {
    pub const HELP: &'static str = Self::HELP_;

    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
